# Generated by Django 5.1.4 on 2025-02-20 09:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_product_discount_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photos', models.JSONField(default=list)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('available_units', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('published', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activities', models.ManyToManyField(blank=True, limit_choices_to={'category__in': ['tourism', 'restaurant']}, related_name='activity_packages', to='product.product')),
                ('flight', models.ForeignKey(limit_choices_to={'category': 'flight'}, on_delete=django.db.models.deletion.PROTECT, related_name='flight_packages', to='product.product')),
                ('hotel', models.ForeignKey(limit_choices_to={'category': 'hotel'}, on_delete=django.db.models.deletion.PROTECT, related_name='hotel_packages', to='product.product')),
            ],
        ),
    ]
