# Generated by Django 5.1.4 on 2025-02-20 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trippackage',
            options={'ordering': ['-created_at']},
        ),
    ]
