# Generated by Django 4.2.17 on 2025-03-02 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('package', '0002_alter_trippackage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='trippackage',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='trippackage',
            name='ratings_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trippackage',
            name='ratings_sum',
            field=models.FloatField(default=0.0),
        ),
    ]
