# Generated by Django 5.1.4 on 2025-03-04 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_transaction_purchasehistory'),
        ('package', '0004_packagerating'),
    ]

    operations = [
    ]
