# Generated by Django 5.1.4 on 2025-02-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('flight', 'Flight Ticket'), ('train', 'Train Ticket'), ('bus', 'Bus Ticket'), ('hotel', 'Hotel'), ('tourism', 'Tourism Ticket'), ('restaurant', 'Restaurant')], max_length=100),
        ),
    ]
