name: Create/Update Test Environment

on:
  push:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: SSH and Deploy
        uses: appleboy/ssh-action@v1.3.1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/user01/backend

            # Pull latest changes
            git pull origin master

            # Build the backend image
            docker build -t backend:v1.0.0

            cd /home/user01/infra
            
            # Stop the containers
            docker-compose down
            
            # Start the test containers
            docker-compose -f docker-compose.backend.yml up -d
